### ISSUE TITLE
备忘录

### ISSUE THREAD

**Issue by TehporP** [DeckerCHAN/TerminologyLauncher#2]
2015 10 03
1.能不能增加自动检测所有instance版本的功能？就比如运行启动器的时候自动检测json？然后加上一个按钮 一按就能再次检查所有instance版本的那种玩意
2.启动器的名字就不用想中文了 英语逼格足够吓死一堆小学生了
3.如果玩家ID低于4个字符 启动器无法打开 显示：状态不正确     别问我为什么  一个ID叫tqq的玩家被迫改名

**Comment by DeckerCHAN** [comment]
7.是什么意思？
8.有点难度

**Comment by TehporP** [comment]
7就是把右上角那个毫无存在感的更新启动器的小圈圈改成文字……

**Comment by DeckerCHAN** [comment]
OK

**Comment by DeckerCHAN** [comment]
mojong通用协议允许的最小用户名是4个字符以上，低于四个字符的有无法支持（肯定注册不了mojong的用户）

**Comment by DeckerCHAN** [comment]
所有功能已经实现！
