### ISSUE TITLE
提示刷屏

### ISSUE THREAD

**Issue by Anikilulala** [DeckerCHAN/TerminologyLauncher#3]
游戏中，不断弹出“自定义皮肤加载器 图形化界面”提示。
截图我在LD的QQ群里发过

**Comment by DeckerCHAN** [comment]
这个问题每次都出现么，你使用什么系统，什么java版本？

**Comment by TehporP** [comment]
那玩意是皮肤插件→_→ 你只要进入这个窗口随便设置一下就行
