### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Cyl18** [DeckerCHAN/TerminologyLauncher#6]
## 1 文件整合

[ILMerge](https://www.microsoft.com/en-us/download/details.aspx?id=17630) 可以把一堆文件整合到一个文件（Dll）

> ILMerge is a utility for merging multiple .NET assemblies into a single .NET assembly. It works on executables and DLLs alike and comes with several options for controlling the processing and format of the output. See the accompanying documentation for details.

在 VS 里面使用 **Post-build event command line** （在 Properties - Build Events 里）即可
## 2 多余 Debug 文件

多出来的 Debug 可以用命令行参数解决，有-debug参数就

```
    [DllImport("kernel32.dll")]
    internal static extern bool AllocConsole();

    [DllImport("kernel32.dll")]
    internal static extern bool FreeConsole();
```

**Comment by DeckerCHAN** [comment]
Feel free to fork, edit and commit a pull request.

**Comment by Cyl18** [comment]
Use "Fody.Costura" to fix problem1. It's very easy, just install a nuget package.
